project:
  type: website
  output-dir: docs   

format:
  revealjs:         
    theme: serif
    footer: "Duke University - Department of Statistical Science"
    logo: images/logo_hollyc.svg
    transition: convex



